name: Market Data Auto-Update

on:
  schedule:
    # 매주 월~금, 한국 시간 오후 6시 10분 (UTC 기준 오전 9시 10분) 실행
    - cron: '10 9 * * 1-5'
  workflow_dispatch: # 내가 원할 때 수동으로 버튼을 눌러 실행할 수 있게 해줌

jobs:
  build:
    runs-on: ubuntu-latest # 리눅스 가상 컴퓨터 사용

    steps:
      - name: 내 코드 가져오기
        uses: actions/checkout@v4

      - name: 파이썬 설치하기
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # 파이썬 버전 지정

      - name: 필요 라이브러리 설치하기
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 파이썬 코드 실행하기!
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          DATABASE_ID: ${{ secrets.DATABASE_ID }}
        run: python main.py
